server {
    listen 80 default;
     server_name www.connectx.co.in connectx.co.in;
   # server_name yourdomain.com; # Replace with your domain or IP address

    root /var/lib/jenkins/workspace/connectx_admin_react/dist; # Directory where the React build files are located
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    error_page 404 /index.html;

    # Optional: Gzip compression to improve performance
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_proxied no-cache no-store private expired auth;
    gzip_min_length 256;
}